### PR TITLE
Added support for IBM s390x architecture.

### PR DESCRIPTION
**Pull request by bschonec**
Added four parameters that are used when running zLinux on IBM s390/s390x architecture.

### CODE REVIEW

**Comment by robruma** [comment]
@bschonec the tests failed with minor lining errors it seems... can you push a fix to your branch?

**Comment by bschonec** [comment]
I'm afraid I don't see where the alignment issues are.  Also, I'm pretty new at this.  Could you show me where the alignment issues you see are occurring or show me how to get that information myself?

**Comment by robruma** [comment]
@bschonec the simplest way is to check out the Travis CI build output here: https://travis-ci.org/huit/puppet-ilmt/jobs/57470486 otherwise you may want to add a style and syntax checker specific to your editor.

**Comment by bschonec** [comment]
Still failing the Travis build but I have no idea why.  I cleaned up the white space per your request.  Again, I'm quite inexperienced at this.

**Comment by tfhartmann** [comment]
@bschonec you can also run "rake lint spec" in the module directory after running "bundle install"  to run the tests locally

**Comment by bschonec** [comment]
Other than missing documentation, I'm not getting any errors in my test.  Can this be merged in now?

**Pull request closed without merging**
